// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHpTZWqbke76GUcmUbiLWmDH_W0Sbukk',
    appId: '1:472064972111:web:96feaaa44463af3255613a',
    messagingSenderId: '472064972111',
    projectId: 'talha-f4180',
    authDomain: 'talha-f4180.firebaseapp.com',
    storageBucket: 'talha-f4180.firebasestorage.app',
    measurementId: 'G-E1HH022VLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90QyiwKDLq3xo0VG3JZ7Ou-T9FTgdico',
    appId: '1:472064972111:android:5f9da4da3b2cdb6355613a',
    messagingSenderId: '472064972111',
    projectId: 'talha-f4180',
    storageBucket: 'talha-f4180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5sQBEkve7_jBY_9XcCJ0xthb0tti8nAg',
    appId: '1:472064972111:ios:0670eb4b90c684e555613a',
    messagingSenderId: '472064972111',
    projectId: 'talha-f4180',
    storageBucket: 'talha-f4180.firebasestorage.app',
    iosBundleId: 'com.example.talhaPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5sQBEkve7_jBY_9XcCJ0xthb0tti8nAg',
    appId: '1:472064972111:ios:0670eb4b90c684e555613a',
    messagingSenderId: '472064972111',
    projectId: 'talha-f4180',
    storageBucket: 'talha-f4180.firebasestorage.app',
    iosBundleId: 'com.example.talhaPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtHpTZWqbke76GUcmUbiLWmDH_W0Sbukk',
    appId: '1:472064972111:web:95e637741b67892455613a',
    messagingSenderId: '472064972111',
    projectId: 'talha-f4180',
    authDomain: 'talha-f4180.firebaseapp.com',
    storageBucket: 'talha-f4180.firebasestorage.app',
    measurementId: 'G-PYKPBXNDM0',
  );
}
